version: '3'

services:

  postgis:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - postgis_data:/var/lib/postgresql
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_PASS: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: postgis

  web:
    image: intelligems/geodjango:latest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DEBUG: "True"
      SECRET_KEY: 'abcd'
      DATABASE_URL: postgresql://postgres:@postgis:5432/postgis
#      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - 8000:8000
    depends_on:
      - postgis

volumes:
  postgis_data: {}