# Generated by Django 3.1.1 on 2020-09-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inc',
            name='description',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
