# Generated by Django 3.1.1 on 2020-09-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_inc_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inc',
            new_name='Shop',
        ),
    ]
